limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/s;

server {
    listen 80;

    # Ο εσωτερικός DNS του Docker για να βρίσκει τα containers
    resolver 127.0.0.11 valid=30s;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Δυναμική σύνδεση με το Backend
    location /api/ {
        set $upstream_backend backend;
        limit_req zone=mylimit burst=10 nodelay;
        proxy_pass http://$upstream_backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Δυναμική σύνδεση με το Frontend
    location / {
        set $upstream_frontend frontend;
        proxy_pass http://$upstream_frontend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}